---
- hosts: all
  become: true
  roles:
    - package_update
    - base_packages
    - users
    - google_chrome
    - vscode
    - dbeaver
    - golang
    - rust
    - nodejs
    - php
    - nginx
    - postgresql
    - mysql
    - docker
    - virtualbox
    - java
    - anydesk
    - teamviewer
    - telegram
    - vlc
    - gnome_shell
    - protobuf
    - vmware-player