- name: add vscode sign key
  tags:
    - vscode
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/microsoft.gpg
    state: present

- name: add vscode apt repository
  tags: 
    - vscode
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] http://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
    update_cache: yes

- name: Install VsCode
  tags:
    - vscode
  apt:
    name: code

- name: Copy VsCode desktop entry
  tags:
    - vscode
  copy:
    src: code.desktop
    dest: /usr/share/applications/code.desktop
    owner: root
    group: root
    mode: 0644