- include_vars: "users.yml"
  tags: always

- name: download nvm installer script
  tags:
    - nodejs
    - nvm
  become_user: "{{users.sysadmin.username}}"
  get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh"
    dest: "{{users.sysadmin.home_dir}}/nvm-install.sh"
    owner: "{{users.sysadmin.username}}"
    group: "{{users.sysadmin.username}}"
    mode: 0755

- name: install nvm
  tags:
    - nodejs
    - nvm
  become_user: "{{users.sysadmin.username}}"
  shell:
    cmd: "{{users.sysadmin.home_dir}}/nvm-install.sh"

- name: reload zshrc
  tags:
    - nodejs
    - nvm
  when: users.sysadmin.shell == "zsh"
  become_user: "{{users.sysadmin.username}}"
  shell:
    cmd: "source {{users.sysadmin.home_dir}}/.zshrc"
  args:
    executable: /bin/zsh

- name: install nodejs LTS version
  tags:
    - nodejs
  become_user: "{{users.sysadmin.username}}"
  shell:
    cmd: "source ~/.zshrc && nvm install --lts"
  args:
    executable: /bin/zsh