- name: Zsh
  tags: 
    - zsh
  apt:
    name: zsh

- name: change user shell to zsh
  tags: 
    - zsh
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: create .zshfunc directory to add more functions to zsh
  tags:
    - zsh
  file:
    path: "{{ user_home_dir }}/.zshfunc"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0755

- name: Clone Oh My ZSH repo.
  tags:
    - zsh
    - ohmyzsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ user_home_dir }}/.oh-my-zsh"
    update: true
    accept_hostkey: true
    version: "master"

- name: copy .zshrc file
  tags: 
    - zsh
    - ohmyzsh
  copy:
    src: zshrc
    dest: "{{ user_home_dir }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644