- name: add teamviewer sign key
  tags: teamviewer
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    keyring: /usr/share/keyrings/teamviewer.gpg
    state: present

- name: add teamviewer apt repository
  tags: teamviewer
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/teamviewer.gpg] https://linux.teamviewer.com/deb stable main
    state: present
    filename: teamviewer
    update_cache: yes
  
- name: install teamviewer
  tags: teamviewer
  apt:
    name: teamviewer
    state: latest