- include_vars: "users.yml"
  tags: always

- name: install requirements
  tags: docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker sign key
  tags:
    - docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: add docker apt repository
  tags: 
    - docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker
    update_cache: yes

- name: install docker
  tags: docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: add docker group
  tags: docker
  group:
    name: docker
    system: no

- name: add docker user to sysadmin gorup
  tags: docker
  user:
    name: docker
    append: yes
    groups: "docker,{{users.sysadmin.group}},sudo,root"
