- name: Install base packages
  apt:
    name:
      - curl
      - git
      - vim
      - openconnect
      - openvpn
      - build-essential
      - openssh-server
      - zsh
      - acl
      - python3-pip
      - unzip
